### PR TITLE
[WIP]fix: make * selector with :first-letter right

### PR DESCRIPTION
**Pull request by Priestch**
@MurakamiShinyu I try to make * selector work with :first-letter.
The submitted code yields the right result, but may not be the right way to fix the issue, could you give me more guidance to finish this PR? I tried hard to understand the whole process, but still can't get the whole picture.

### CODE REVIEW

**Comment by MurakamiShinyu** [comment]
Thanks @Priestch. I confirmed that your fix works for the following case:

```html
<style>
  *::first-letter {
    color: blue;
  }
</style>
<body>
  <h1>Foo bar</h1>
</body>
```

(from Issue https://github.com/vivliostyle/vivliostyle.js/issues/566#issuecomment-171152105)

However, it does not work when `<h1>` is not a child element of the `<body>`:

```html
<style>
  *::first-letter {
    color: blue;
  }
</style>
<body>
  <section>
    <h1>Foo bar</h1>
  </section>
</body>
```

**Comment by MurakamiShinyu** [comment]
A suggestion:

Change
https://github.com/vivliostyle/vivliostyle.js/blob/897572926077069b0aec6e898966b6443573c7da/packages/core/src/vivliostyle/vgen.ts#L219-L227

to

```ts
        if (name.match(/^first-/)) {
          const display = computedStyle["display"];
          if (!display || display === Css.ident.inline) {
            continue;
          }
          const child = element.firstElementChild;
          if (child && !child.previousSibling?.textContent.trim()) {
            const childStyle = styler.getStyle(child, false);
            if (childStyle) {
              const childDisplay = CssCascade.getProp(childStyle, "display");
              if (
                childDisplay?.value &&
                childDisplay.value !== Css.ident.inline
              ) {
                continue;
              }
            }
          }
        }
```

**Comment by MurakamiShinyu** [comment]
By the way, I found a related bug. The selector `::first-letter` must be equivalent to `*::first-letter`. However, in the current implementation, the selector `::first-letter` causes error ("CSS parser: E_CSS_SYNTAX" in console) and the style rule is  ignored.

I am going to make another PR that fix these pseudo element related bugs.

**Comment by MurakamiShinyu** [comment]
@Priestch I made a new PR

- #974

that replaces this PR, so I close this. Please check the new PR. Thanks!

**Comment by Priestch** [comment]
Ok, I will check. and I'm happy to participate.

**Pull request closed without merging**
