### PR TITLE
add paper sizes

### PR DESCRIPTION
**Pull request by Crissov**
- in addition to those required by [css-page](https://drafts.csswg.org/css-page-3/#typedef-page-size-page-size)
- these have been proposed for addition in https://github.com/w3c/csswg-drafts/issues/4722
- complete ISO 216 A, B and C series
- JIS P 0202 B series

### CODE REVIEW

**Comment by MurakamiShinyu** [comment]
Thanks for the PR.

Adding new page size values will be ok, but to enable these values, the `PAGE_SIZE` definition in [core/src/vivliostyle/assets.ts](https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/core/src/vivliostyle/assets.ts) has to be also updated:

https://github.com/vivliostyle/vivliostyle.js/blob/97c980e5361c9c5a20fb55a9c261a58eaa754a2e/packages/core/src/vivliostyle/assets.ts#L514

Vivliostyle Viewer's User Style Preferences has also Page Size menu:
 
Screen Shot 2021-04-05 at 16 20 15

These Page Size menu items are defined in [viewer/src/models/page-style.ts](https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/viewer/src/models/page-style.ts):

https://github.com/vivliostyle/vivliostyle.js/blob/97c980e5361c9c5a20fb55a9c261a58eaa754a2e/packages/viewer/src/models/page-style.ts#L42-L53

However, if we add all new page sizes to this menu, it may become difficult to use because there are too many items that are rarely used. What do you think?

BTW, we have [Commit Message Guideline](https://github.com/vivliostyle/vivliostyle.js/blob/master/CONTRIBUTING.md#commit-message-guideline). Commit messages such as "feat: add paper sizes" are preferable.

**Comment by MurakamiShinyu** [comment]
I am testing Vivliostyle Viewer's Page Size menu with all new page sizes. I think It looks ok:

Screen Shot 2021-04-07 at 1 34 35

**Review by MurakamiShinyu — APPROVED** [review]

**Comment by Crissov** [comment]
The list is a bit long indeed and entries should perhaps be nested (US/ISO/JIS or US/A/B/C).

At least the two B series should be disambiguated in the same way: either suffix or prefix.

**Comment by MurakamiShinyu** [comment]
The new Page Size menu is now available in the Canary version of Vivliostyle Viewer: https://vivliostyle.now.sh/
and now I am preparing the v2.7.0 release, which includes this #713 (thanks @Crissov), and #714.

Further improvements may be needed, but they can be made in subsequent releases. Contributions are most welcome.

> At least the two B series should be disambiguated in the same way: either suffix or prefix.

[CSS page sizes](https://drafts.csswg.org/css-page-3/#typedef-page-size-page-size) are "B5" and "JIS-B5" etc. I think that many users of Vivliostyle Viewer are also stylesheet authors, and using CSS page size keywords in the menu will be useful for them. However, in Japan, "B5" usually means "JIS-B5", so I put "(ISO)" for ISO B series to avoid misuse.

**Pull request merged**
